// Curated documentation only; defaults and responsive values come from variables.css.
const kinds = {
  scale: { values: 'Number from 0 to 2; lower is more transparent, 1 is the default', property: 'opacity', examples: ['0', '.7', '1', '2'] },
  display: { values: 'flex (visible) or none (hidden)', property: 'display', examples: ['flex', 'none'] },
  opacity: { values: 'Number from 0 (transparent) to 1 (opaque)', property: 'opacity', examples: ['.45', '.6', '1'] },
  color: { values: 'Color: hex, rgb/rgba, hsl/hsla, or a name such as white', property: 'color', examples: ['#f5f5f7', 'rgba(255,255,255,.65)'] },
  paint: { values: 'Background: a color, gradient, layered backgrounds, or none', property: 'background', examples: ['#22222680', 'rgba(34,34,38,.65)'] },
  image: { values: 'CSS image: a gradient or none', property: 'mask-image', examples: ['linear-gradient(to bottom,#000,transparent)', 'none'] },
  length: { values: 'Size of 0 or greater in px, rem, vw, or svh; min(), max(), and clamp() also work', property: 'width', examples: ['16px', '24px'] },
  size: { values: 'Size of 0 or greater in CSS units or a percentage', property: 'width', examples: ['50%', '100%'] },
  signed: { values: 'Positive or negative CSS size/percentage; calc() also works', property: 'top', examples: ['-2px', '0px', '2px'] },
  radius: { values: 'Corner radius of 0 or greater in CSS units or a percentage', property: 'border-radius', examples: ['14px', '20px'] },
  font: { values: 'Comma-separated font families; quote names containing spaces', property: 'font-family', examples: ['"Inter Variable", sans-serif', 'system-ui, sans-serif'] },
  weight: { values: 'Text thickness from 100 to 900 with Inter; higher is bolder', property: 'font-weight', examples: ['400', '650', '700'] },
  leading: { values: 'Line spacing multiplier such as 1.5, or normal', property: 'line-height', examples: ['1.2', '1.5', 'normal'] },
  tracking: { values: 'CSS letter-spacing length, including negative values, or normal', property: 'letter-spacing', examples: ['-0.02em', '0px', 'normal'] },
  shadow: { values: 'CSS shadow list (offsets, blur, spread, color), or none', property: 'box-shadow', examples: ['0 10px 28px -14px #000c', 'none'] },
  filter: { values: 'Background filters such as blur() and saturate(), or none', property: 'backdrop-filter', examples: ['blur(24px) saturate(160%)', 'none'] },
  easing: { values: 'Animation curve such as ease-out, cubic-bezier(), or steps()', property: 'transition-timing-function', examples: ['ease-out', 'cubic-bezier(.2,.8,.2,1)'] },
  time: { values: 'Duration of 0 or greater in milliseconds (ms) or seconds (s)', property: 'transition-duration', examples: ['200ms', '0ms'] },
  grid: { values: 'CSS column layout using lengths, fr (a share of space), repeat(), or minmax()', property: 'grid-template-columns', examples: ['repeat(2,minmax(0,1fr))', 'minmax(0,1fr)'] },
  position: { values: 'CSS position keywords, percentages, or lengths', property: 'object-position', examples: ['center top', '50% 50%'] },
  layer: { values: 'Whole-number stacking order (higher is in front), or auto', property: 'z-index', examples: ['1', '2', 'auto'] },
  fixed: { values: 'Internal constant; keep 1', property: null, examples: ['1'] }
};

export const groups = [
  { id: 'optional', label: 'Optional Features', rows: [
    ['glass-opacity-scale','Glass transparency','Multiplies glass background opacity without fading text or changing blur.','scale'],
    ['format-badges-display','Format badges','Shows or hides the optional plugin’s detail-page format badges.','display'],
    ['icon-state-duration','Play/Pause animation','Sets how long the icon animates when playback changes between Play and Pause.','time'],
    ['admin-brand-inset','Dashboard brand padding','Insets the Dashboard server-brand tile from the sidebar’s top and side.','length'],
    ['feature-logo-height','Featured logo height','Limits featured logos by the viewport height to keep short screens readable.','length']
  ] },
  { id: 'forms', label: 'Forms, dialogs & administration', rows: [
    ['form-field-width','Form field width','Sets the width of ordinary field groups including their labels and help text.','size'],
    ['form-field-min-width','Form field minimum width','Keeps ordinary fields readable without exceeding their container.','length'],
    ['favorite-color','Favorite heart color','Colors filled hearts for favorited media, including hover and keyboard focus.','color'],
    ['field-radius','Field corners','Rounds text inputs, selectors, and compact form buttons.','radius'],
    ['field-height','Standard field height','Sets the minimum height of standard form fields.','length'],
    ['field-padding','Field text padding','Sets horizontal spacing inside standard form fields.','length'],
    ['field-bg','Field glass','Sets the translucent background of standard inputs.','paint'],
    ['field-hover','Field hover surface','Sets the background of hovered form fields.','paint'],
    ['field-border','Field borders','Colors field outlines and unchecked control borders.','color'],
    ['field-placeholder','Field placeholder text','Colors placeholder text inside standard inputs.','color'],
    ['primary-glass','Primary form action glass','Colors primary form actions and checked controls.','color'],
    ['danger','Destructive and error text','Colors destructive actions and invalid-field labels.','color'],
    ['danger-bg','Destructive action surface','Sets the tinted background of destructive actions and error alerts.','paint'],
    ['success','Success text','Colors success notifications.','color'],
    ['disabled-opacity','Disabled control opacity','Sets the opacity of disabled controls.','opacity'],
    ['touch-target','Minimum touch target','Sets the minimum clickable area of shared buttons and menu rows.','length'],
    ['dialog-glass','Dialog glass','Sets the translucent background of menus, dialogs, and player statistics.','paint'],
    ['dialog-clearance','Dialog viewport clearance','Keeps dialogs away from viewport edges.','length'],
    ['dialog-available-width','Dialog available width','Limits dialog width to the viewport minus its edge clearance.','length'],
    ['dialog-available-height','Dialog available height','Limits dialog height to the viewport minus its edge clearance.','length'],
    ['dialog-menu-width','Action menu maximum width','Limits the width of Jellyfin pop-up action menus.','length'],
    ['dialog-editor-width','Editor maximum width','Limits the width of larger editing dialogs.','length'],
    ['dialog-footer-bg','Dialog header and footer glass','Sets the background behind dialog titles and footer actions.','paint'],
    ['dialog-backdrop','Dialog background dimming','Colors the dimming layer behind administration dialogs.','color'],
    ['admin-row-height','Administration row height','Sets the minimum height of compact administration rows.','length'],
    ['admin-gap','Administration spacing','Sets compact panel padding and form spacing in Settings and Dashboard.','length'],
    ['admin-content-width','Dashboard content width','Limits Dashboard page width within the area beside the sidebar.','size'],
    ['admin-form-width','Settings form width','Limits user Settings form width without narrowing Dashboard pages.','length'],
    ['admin-page-gutter','Dashboard side spacing','Sets the left and right padding inside Dashboard pages.','length'],
    ['admin-page-top-gap','Dashboard header clearance','Adds space below Jellyfin’s header before Dashboard content starts.','length'],
    ['admin-panel-bg','Administration panel glass','Sets the background of administration cards and Settings rows.','paint'],
    ['admin-table-stripe','Table row tint','Sets a subtle background on alternating administration table rows.','paint'],
    ['admin-table-min-width','Table minimum width','Keeps wide tables readable while their container scrolls horizontally.','length'],
    ['stats-width','Playback statistics width','Limits the width of the native playback statistics panel.','length'],
    ['multiline-height','Multiline input height','Sets the minimum height of textareas such as Custom CSS and metadata.','length']
  ] },
  { id: 'materials', label: 'Colors, glass & animation', rows: [
    ['companion-contract','Compatibility marker (internal)','Allows the plugin to recognize compatible CSS and must stay at 1.','fixed'],
    ['dashboard-contract','Dashboard compatibility marker (internal)','Allows administration styling only with the shared UI modules and must stay at 1.','fixed'],
    ['bg','Page background','Sets the background color behind Jellyfin pages.','color'],
    ['surface','Content surfaces','Colors standard content surfaces, including Library and Search.','paint'],
    ['surface-raised','Raised panels','Colors the higher-contrast panels used above the page background.','paint'],
    ['text','Primary text','Colors primary text and the Search caret.','color'],
    ['text-secondary','Secondary text','Colors descriptions, secondary labels, and metadata.','color'],
    ['text-tertiary','Tertiary text (reserved)','Reserves a dimmer text color with no current visual effect.','color'],
    ['text-on-image','Text over artwork','Colors metadata displayed directly over artwork.','color'],
    ['primary-bg','Primary button background','Sets the background of primary actions such as Play.','paint'],
    ['primary-text','Primary button text','Colors text and icons inside primary actions.','color'],
    ['secondary-bg','Secondary button background','Sets the background of secondary native actions.','paint'],
    ['secondary-hover','Secondary button hover','Sets the background when secondary native actions are hovered.','paint'],
    ['border','Standard borders','Colors shared input and panel borders.','color'],
    ['hairline','Hairline borders','Colors subtle separators in dialogs and filter accordions.','color'],
    ['transparent','Transparent surfaces','Supplies the transparent color used by borderless surfaces.','color'],
    ['control-blur','Control glass blur','Controls background blur and color intensity behind translucent controls.','filter'],
    ['ease','Animation easing','Controls how theme animations speed up and slow down.','easing'],
    ['motion-duration','Hover animation speed','Sets the duration of ordinary hover and control transitions.','time'],
    ['reduced-duration','Reduced-motion duration','Supplies the animation duration used when reduced motion is enabled.','time'],
    ['shadow-card','Card shadow','Sets the shadow beneath hoverable cards.','shadow'],
    ['shadow-panel','Panel shadow','Sets the shadow around large floating panels.','shadow'],
    ['shadow-control','Control shadow','Sets the inner highlight or shadow on controls.','shadow']
  ] },
  { id: 'typography', label: 'Text & fonts', rows: [
    ['font','Body fonts','Lists the preferred and fallback fonts for body text and controls.','font'],
    ['font-display','Heading fonts','Lists the preferred and fallback fonts for prominent headings and titles.','font'],
    ['font-size','Base text size','Sets the default text size on Jellyfin pages.','length'],
    ['body-weight','Body text weight','Controls the thickness of ordinary body text.','weight'],
    ['control-weight','Button text weight','Controls the thickness of button and control labels.','weight'],
    ['heading-weight','Heading weight','Controls the thickness of section headings.','weight'],
    ['title-weight','Title weight','Controls the thickness of prominent item titles.','weight'],
    ['body-leading','Body line spacing','Controls vertical spacing between lines of descriptive text.','leading'],
    ['title-leading','Title line spacing','Controls vertical spacing between lines of large titles.','leading'],
    ['title-tracking','Title letter spacing','Controls spacing between letters in prominent titles.','tracking'],
    ['control-tracking','Control letter spacing','Controls spacing between letters in button labels.','tracking'],
    ['control-font-size','Button text size','Sets the size of ordinary button and control labels.','length'],
    ['small-font-size','Metadata text size','Sets the size of small labels and metadata.','length'],
    ['section-font-size','Section heading size','Sets the size of shelf and section headings.','length'],
    ['title-size','Detail title size','Sets the text size of detail titles when no artwork logo is used.','length']
  ] },
  { id: 'navigation', label: 'Navigation & keyboard focus', rows: [
    ['nav-height','Header height','Sets the header height and related content offsets.','length'],
    ['nav-scrim','Header gradient','Sets the fading background behind the top header.','paint'],
    ['focus-color','Keyboard focus color','Colors keyboard focus outlines and focused input borders.','color'],
    ['focus-width','Keyboard focus thickness','Sets the thickness of keyboard focus outlines.','length'],
    ['focus-offset','Keyboard focus spacing','Sets the distance between a control and its focus outline.','length'],
    ['nav-glass','Navigation glass','Sets the translucent background of the navigation drawer.','paint'],
    ['nav-solid','Unblurred navigation background','Sets the background used when the browser cannot blur translucent controls.','paint'],
    ['nav-width','Drawer width','Sets the width of the navigation drawer.','length'],
    ['nav-radius','Drawer corners','Controls the roundness of the navigation drawer.','radius'],
    ['nav-inset','Drawer vertical inset','Sets the gap between the drawer and the top and bottom edges.','length'],
    ['nav-inline-inset','Drawer side inset','Sets the drawer’s distance from the side of the window.','length'],
    ['nav-row-height','Drawer row height','Sets the minimum height of each navigation destination.','length'],
    ['nav-selection','Selected destination background','Colors the active destination in the navigation drawer.','paint'],
    ['nav-selection-text','Selected destination text','Colors text and icons in the active drawer destination.','color'],
    ['nav-border','Drawer border','Colors the outline of the navigation drawer.','color'],
    ['header-scrolled','Scrolled header background','Sets the header background after the page is scrolled.','paint'],
    ['chrome-glass','Header control glass','Sets the background of grouped header controls.','paint'],
    ['home-chrome-glass','Home header glass','Sets the translucent header-control background on Home.','paint'],
    ['home-selected-glass','Home selected tab','Sets the background of the selected Home tab.','paint'],
    ['home-secondary-glass','Home secondary actions','Sets the layered glass background of secondary Home actions.','paint'],
    ['home-secondary-hover-glass','Home secondary hover','Sets the glass background when secondary Home actions are hovered.','paint'],
    ['home-glass-border','Home glass border','Colors the outline of glass controls on Home.','color'],
    ['chrome-hover','Header control hover','Sets the background when header controls are hovered.','paint'],
    ['chrome-border','Header control border','Colors the outline of header controls.','color'],
    ['chrome-border-width','Header border thickness','Sets the thickness of header-control borders.','length'],
    ['chrome-icon-size','Header icon size','Sets the size of shapes inside header controls.','length'],
    ['chrome-button-size','Header button size','Sets the width and height of circular header buttons.','length'],
    ['chrome-group-gap','Header button spacing','Sets spacing between controls in a header group.','length'],
    ['chrome-tab-height','Header tab height','Sets the height of navigation tabs in the header.','length'],
    ['chrome-group-padding','Header group padding','Sets the space inside each header-control group.','length']
  ] },
  { id: 'cards', label: 'Cards & shared spacing', rows: [
    ['gutter','Page side padding','Sets the shared side padding around content and artwork text.','length'],
    ['space-xs','Extra-small spacing','Sets the smallest shared gap and padding size.','length'],
    ['space-sm','Small spacing','Sets small shared gaps and control padding.','length'],
    ['space-md','Medium spacing','Sets medium shared gaps and control padding.','length'],
    ['space-lg','Large spacing','Sets large shared gaps and section padding.','length'],
    ['section-space','Section spacing','Sets the breathing room between shelves and large sections.','length'],
    ['card-gap','Shelf card spacing','Sets spacing between cards in native shelves.','length'],
    ['library-grid-gap','Library grid spacing','Sets spacing between posters in Library grids.','length'],
    ['poster-width','Shelf poster width','Sets the width of posters in layouts that use the shared card width.','length'],
    ['landscape-width','Landscape card width','Sets the shared width of landscape cards.','length'],
    ['person-width','Cast portrait width','Sets the width of cast and person cards.','length'],
    ['card-lift','Card hover lift','Moves cards vertically when hovered.','signed'],
    ['radius-small','Small corners','Controls rounding on small controls and badges.','radius'],
    ['radius-card','Card corners','Controls rounding on artwork cards and poster surfaces.','radius'],
    ['radius-panel','Panel corners','Controls rounding on larger panels and grouped controls.','radius'],
    ['radius-pill','Pill corners','Controls rounding on pill-shaped buttons and circular controls.','radius'],
    ['control-height','Shared button height','Sets the minimum height of ordinary theme buttons.','length'],
    ['control-padding','Shared button padding','Sets horizontal padding inside ordinary theme buttons.','length'],
    ['overlay-scrim','Artwork hover gradient','Darkens artwork behind the buttons shown when you hover a card.','paint'],
    ['progress-height','Watched-progress thickness','Sets the thickness of progress strips on cards.','length'],
    ['progress-track','Watched-progress track','Colors the unfilled portion of card progress strips.','paint'],
    ['poster-actions-bg','Poster action glass','Sets the glass background around grouped poster buttons.','paint'],
    ['poster-action-size','Poster action button size','Sets the size of secondary buttons inside poster overlays.','length'],
    ['poster-play-size','Poster Play button size','Sets the size of the main Play button on poster overlays.','length'],
    ['poster-action-gap','Poster action spacing','Sets spacing between the grouped poster buttons.','length'],
    ['poster-action-inset','Poster action edge spacing','Keeps the grouped buttons away from the poster’s bottom and right edges.','length'],
    ['poster-action-padding','Poster action padding','Sets space inside the glass group around poster buttons.','length']
  ] },
  { id: 'artwork', label: 'Artwork & featured Home', rows: [
    ['hero-height','Detail artwork height','Sets the height of the large artwork area on detail pages.','length'],
    ['hero-content-width','Detail content width','Limits the width of primary detail-page content.','length'],
    ['hero-overview-width','Overview width','Limits the width of descriptions over hero artwork.','length'],
    ['hero-scrim','Detail artwork gradient','Sets the gradients that keep detail text readable over artwork.','paint'],
    ['detail-background','Detail page background','Sets the background transition beneath detail artwork.','paint'],
    ['backdrop-mask','Backdrop fade','Controls how global backdrop artwork fades into the page.','image'],
    ['logo-width','Artwork logo width','Sets the width of transparent title-logo artwork.','length'],
    ['logo-height','Artwork logo height','Limits the height of title-logo artwork and related detail spacing.','length'],
    ['logo-top','Detail logo top offset','Positions title-logo artwork vertically on detail pages.','length'],
    ['logo-layer','Detail logo stacking','Sets the stacking order of the detail logo.','layer'],
    ['image-position','Artwork crop position','Selects which part of artwork stays visible when it is cropped.','position'],
    ['feature-height','Featured Home height','Sets the height of the optional plugin’s Home carousel.','length'],
    ['feature-title-size','Featured title size','Sets the text size of featured titles when no logo is available.','length'],
    ['feature-content-width','Featured content width','Limits the width of text and actions in the Home carousel.','length'],
    ['feature-scrim','Featured artwork gradient','Sets the gradients behind featured text and controls.','paint'],
    ['feature-gradient','Featured fallback background','Sets the carousel background beneath its artwork.','paint'],
    ['feature-dot','Inactive pagination color','Colors inactive carousel pagination indicators.','paint'],
    ['feature-dot-active','Active pagination color','Colors the selected carousel pagination indicator.','paint'],
    ['feature-dot-size','Pagination dot size','Sets the size of inactive carousel pagination dots.','length'],
    ['feature-dot-active-width','Active pagination width','Sets the width of the selected pagination indicator.','length'],
    ['feature-slide-duration','Carousel animation speed','Sets the duration of the slide animation between featured titles.','time']
  ] },
  { id: 'details', label: 'Details, tracks & episodes', rows: [
    ['episode-image-width','Episode image width','Sets the artwork width in episode cards.','size'],
    ['episode-columns','Episode columns','Sets the number and sizing of episode-card columns.','grid'],
    ['episode-content-columns','Episode content columns (reserved)','Reserves an inner-column layout with no current visual effect.','grid'],
    ['track-surface','Track selector surface','Sets the background of Video, Audio, and Subtitles selectors.','paint'],
    ['track-hover','Track selector hover','Sets the background when track selectors are hovered.','paint'],
    ['track-border','Track selector border','Colors the outline of track selectors.','color'],
    ['track-row-height','Track selector height','Sets the minimum height of each track-selector row.','length'],
    ['track-icon-size','Track icon size','Sets the screen, speaker, and subtitle icon sizes.','length'],
    ['track-label-size','Track label text size','Sets the size of Video, Audio, and Subtitles labels.','length'],
    ['track-label-width','Track label width','Sets the space allocated to track-selector labels.','length'],
    ['track-select-end-padding','Track value end padding','Keeps selected track text away from the dropdown arrow.','length'],
    ['track-badge-pull','Format badge vertical offset','Adjusts the top margin of source-format badges.','signed'],
    ['format-badge-bg','Format badge background','Sets the background of source-format badges.','paint'],
    ['format-badge-border','Format badge border','Colors the outline of source-format badges.','color'],
    ['format-badge-height','Format badge height','Sets the minimum height of source-format badges.','length'],
    ['format-badge-font-size','Format badge text size','Sets the text size inside source-format badges.','length'],
    ['episode-surface','Episode card surface','Sets the background of episode cards.','paint'],
    ['episode-hover','Episode card hover','Sets the background when episode cards are hovered.','paint'],
    ['episode-border','Episode card border','Colors the outline of episode cards.','color'],
    ['episode-action-size','Episode action button size','Sets the size of buttons in the episode action dock.','length'],
    ['episode-dock-padding','Episode dock padding','Sets padding inside the episode action dock.','length'],
    ['episode-dock-gap','Episode dock button spacing','Sets spacing between episode action buttons.','length'],
    ['episode-dock-bg','Episode dock glass','Sets the background of the episode action dock.','paint'],
    ['episode-dock-border','Episode dock border','Colors the outline of the episode action dock.','color'],
    ['episode-card-lift','Episode hover lift','Moves episode cards vertically when hovered.','signed']
  ] },
  { id: 'search-login', label: 'Search & login', rows: [
    ['search-heading-size','Search heading size','Sets the size of headings on Search.','length'],
    ['search-content-width','Search content width','Limits the width of the main Search area.','length'],
    ['search-field-height','Search field height','Sets the height of the Search input field.','length'],
    ['search-field-bg','Search field glass','Sets the background of the Search input field.','paint'],
    ['search-input-font-size','Search text size','Sets the size of text entered into Search.','length'],
    ['search-input-line-height','Search line spacing','Controls vertical line spacing inside the Search field.','leading'],
    ['search-input-padding','Search field padding','Sets the space between Search text and the field edges.','length'],
    ['search-placeholder','Search placeholder color','Colors placeholder text in the Search field.','color'],
    ['search-tile-width','Search tile width','Sets the width of small Search tiles such as genres.','length'],
    ['search-tile-height','Search tile height','Sets the minimum height of small Search tiles.','length'],
    ['login-width','Login panel width','Limits the width of the login form.','length'],
    ['login-padding','Login panel padding','Sets padding inside the login panel.','length'],
    ['login-background','Login background','Sets the login panel background outside Desktop mode.','paint'],
    ['login-desktop-background','Desktop login background','Sets the opaque Desktop login panel independently of glass transparency.','paint'],
    ['login-title-size','Login heading size','Sets the size of the login heading.','length']
  ] },
  { id: 'player', label: 'Player controls', rows: [
    ['player-scrim','Player gradient base','Supplies the dark color used within the bottom player gradient.','color'],
    ['player-top-scrim','Player top gradient','Sets the gradient behind the player’s top controls.','paint'],
    ['osd-glass','Player bottom gradient','Sets the full-width fading background behind the player controls.','paint'],
    ['osd-blur','Player backdrop blur','Controls blur behind the bottom player surface and defaults to none.','filter'],
    ['osd-radius','Player surface corners','Controls rounding on the bottom player surface.','radius'],
    ['osd-padding','Player surface padding','Sets padding around the bottom player controls.','length'],
    ['player-control-size','Player button size','Sets the width and height of the clickable player buttons.','length'],
    ['player-control-gap','Player control gap (reserved)','Reserves a control-spacing value with no current visual effect.','length'],
    ['player-dock-bg','Player dock glass','Sets the translucent background of the two player-control docks.','paint'],
    ['player-dock-border','Player dock border','Colors the outline of player-control docks.','color'],
    ['player-dock-padding','Player dock padding','Sets padding inside player-control docks.','length'],
    ['player-dock-gap','Player dock button spacing','Sets spacing between buttons inside player-control docks.','length'],
    ['player-transport-offset','Transport dock offset','Positions the transport dock relative to the player’s bottom layout.','signed'],
    ['player-icon-size','Player icon size','Sets the size of shapes inside player buttons.','length'],
    ['player-title-size','Player title size','Sets the text size of the title displayed in the player.','length'],
    ['player-timeline-track','Timeline background','Colors the unfilled portion of the playback timeline.','paint'],
    ['player-chapter-tick','Chapter marker color','Colors chapter markers along the timeline.','paint'],
    ['player-control-hover','Player button hover','Sets the background when player buttons are hovered.','paint'],
    ['player-control-active','Active player button','Sets the background of active player controls.','paint'],
    ['player-timeline-height','Timeline thickness','Sets the thickness of the playback timeline.','length'],
    ['player-bottom-padding','Player bottom spacing','Sets extra padding below the player controls.','length']
  ] }
];

export const quickTokens = ['bg','text','nav-glass','control-blur','card-gap','library-grid-gap','radius-card','feature-height','hero-height','feature-title-size','search-input-font-size','player-control-size'].map(name => `--ng-${name}`);
const commonExamples = {
  bg: ['#000','#101014'], text: ['#f5f5f7','#fff'], 'nav-glass': ['#22222680','#18181bd9'],
  'control-blur': ['blur(24px) saturate(160%)','none'], 'card-gap': ['24px','32px'],
  'library-grid-gap': ['24px','40px'], 'radius-card': ['14px','18px'],
  'feature-height': ['70svh','78svh'], 'hero-height': ['88svh','clamp(620px,88svh,1000px)'],
  'feature-title-size': ['48px','clamp(38px,4.8vw,72px)'], 'search-input-font-size': ['20px','24px'],
  'player-control-size': ['44px','48px'],
  'icon-state-duration': ['200ms','0ms'], 'admin-brand-inset': ['12px','16px'],
  'feature-logo-height': ['10svh','12svh'], 'form-field-width': ['50%','100%'],
  'form-field-min-width': ['280px','320px'], 'favorite-color': ['#ff453a','#ff375f'],
  'field-height': ['48px','52px'], 'touch-target': ['44px','48px'],
  'dialog-menu-width': ['24rem','28rem'], 'dialog-editor-width': ['48rem','56rem'],
  'dialog-available-width': ['calc(100vw - 32px)','calc(100vw - 48px)'],
  'dialog-available-height': ['calc(100dvh - 32px)','calc(100dvh - 48px)'],
  'admin-content-width': ['100%','90%'], 'admin-form-width': ['48rem','56rem'],
  'admin-table-min-width': ['40rem','48rem'], 'stats-width': ['28rem','32rem'],
  'multiline-height': ['10rem','14rem'], 'font-size': ['16px','18px'],
  'control-font-size': ['14px','16px'], 'small-font-size': ['12px','14px'],
  'section-font-size': ['24px','28px'], 'title-size': ['48px','64px'],
  'nav-height': ['72px','80px'], 'nav-width': ['16rem','20rem'],
  'nav-radius': ['20px','24px'], 'nav-row-height': ['48px','52px'],
  'chrome-button-size': ['44px','48px'], 'chrome-icon-size': ['20px','24px'],
  'chrome-tab-height': ['44px','48px'], 'poster-width': ['180px','220px'],
  'landscape-width': ['280px','320px'], 'person-width': ['120px','160px'],
  'card-lift': ['-2px','0px'], 'control-height': ['44px','48px'],
  'radius-pill': ['999px','50%'], 'progress-height': ['3px','4px'],
  'poster-action-size': ['44px','48px'], 'poster-play-size': ['44px','48px'],
  'poster-action-gap': ['4px','8px'], 'poster-action-padding': ['6px','10px'],
  'hero-content-width': ['44rem','52rem'], 'hero-overview-width': ['32rem','40rem'],
  'logo-width': ['240px','320px'], 'logo-height': ['120px','160px'],
  'logo-top': ['0px','24px'], 'feature-content-width': ['36rem','44rem'],
  'feature-dot-size': ['6px','8px'], 'feature-dot-active-width': ['22px','28px'],
  'feature-slide-duration': ['650ms','400ms'], 'episode-image-width': ['40%','100%'],
  'track-row-height': ['44px','48px'], 'track-icon-size': ['18px','22px'],
  'track-label-size': ['13px','14px'], 'track-label-width': ['6rem','8rem'],
  'format-badge-height': ['24px','28px'], 'format-badge-font-size': ['11px','13px'],
  'episode-action-size': ['44px','48px'], 'episode-card-lift': ['-2px','0px'],
  'search-heading-size': ['32px','40px'], 'search-content-width': ['60rem','72rem'],
  'search-field-height': ['56px','64px'], 'search-tile-width': ['120px','160px'],
  'search-tile-height': ['44px','56px'], 'login-width': ['22rem','26rem'],
  'login-title-size': ['28px','32px'], 'player-dock-padding': ['6px','10px'],
  'login-desktop-background': ['#202023','#111114'],
  'player-dock-gap': ['3px','6px'], 'player-icon-size': ['21px','24px'],
  'player-title-size': ['18px','22px'], 'player-timeline-height': ['3px','4px']
};
export const tokenDocs = groups.flatMap(group => group.rows.map(([suffix,label,description,kind]) => ({
  name: `--ng-${suffix}`, group: group.id, label, description, ...kinds[kind], examples: commonExamples[suffix] || kinds[kind].examples
})));
